/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica6.pkg2.pkg0;


import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *Esta clase implementa un propertychangelistener y lo que hace es crear una ventana de cuarto por cada paciente creado en el cual se mostraran los valroes actualizados por el listener si se selecciona la casilla correspondiente en el jtable de patientlistWindow(la ventana principal).
 * @author nacho
 */
public class WindowPressureListener extends javax.swing.JFrame implements PropertyChangeListener {
//Declaracion de variables
    private PatientListWindow listWindow;
    private Patient p;

    /**
     * Creates new form WindowPressureListener
     * @param listWindow
     */
    public WindowPressureListener(PatientListWindow listWindow) {
        initComponents();
        this.listWindow = listWindow;
    }

    /**
     *Cuando el property escucha un nuevo cambio hace un set a los labels para cambiarle los valores correspondientes.
     * @param evt
     */
    public void propertyChange(PropertyChangeEvent evt) {
        p = (Patient) evt.getSource();
        patientTextName.setText(p.getName());
        String maxPressure = Double.toString(p.getMaxPressure());
        maxPressureText.setText(maxPressure);
        String minPressure = Double.toString(p.getMinPressure());
        minPressureText.setText(minPressure);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        maxPressureLabel = new javax.swing.JLabel();
        minPressureLabel = new javax.swing.JLabel();
        patientTextName = new javax.swing.JLabel();
        maxPressureText = new javax.swing.JLabel();
        minPressureText = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setTitle("Room Monitor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        patientLabel.setText("Patient:");

        maxPressureLabel.setText("Max Pressure:");

        minPressureLabel.setText("Min Pressure:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minPressureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxPressureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxPressureText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minPressureText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientLabel)
                    .addComponent(patientTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxPressureLabel)
                    .addComponent(maxPressureText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minPressureLabel)
                    .addComponent(minPressureText))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formWindowClosed
//Cuando se cierra la ventana se elimina el checkbox de la ventana principal.
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           listWindow.removeCheckBox(p);
    }//GEN-LAST:event_formWindowClosing

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maxPressureLabel;
    private javax.swing.JLabel maxPressureText;
    private javax.swing.JLabel minPressureLabel;
    private javax.swing.JLabel minPressureText;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JLabel patientTextName;
    // End of variables declaration//GEN-END:variables
}
